### ISSUE TITLE
0.2 version RuntimeException

### ISSUE THREAD

**Issue by EpsilonOrionis** [sahildave/Search-View-Layout#15]
I get: unknown animation alpha, but if I downgrade to 0.1 version it works.

**Comment by sahildave** [comment]
Can you post the stacktrace please?

**Comment by olzhas-ilyubayev** [comment]
I have some problem in my app.
Stacktrace:

```
01-20 21:13:13.667 20575-20575/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.company.app, PID: 20575
                                                   java.lang.RuntimeException: Unknown animator name: alpha
                                                       at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:713)
                                                       at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:664)
                                                       at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:123)
                                                       at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:103)
                                                       at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:88)
                                                       at android.app.FragmentManagerImpl.loadAnimator(FragmentManager.java:826)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                       at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
                                                       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

My layout:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity">

    <ImageView
        android:src="@drawable/background"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"/>

    <android.support.design.widget.AppBarLayout
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:elevation="0dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="horizontal">

            <ImageButton
                android:id="@+id/button"
                android:background="@android:color/transparent"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:src="@drawable/ic_menu_white_24dp" />

            <include layout="@layout/widget_search_bar"/>
        </LinearLayout>

    </android.support.design.widget.AppBarLayout>
</android.support.design.widget.CoordinatorLayout>
```
